### ISSUE TITLE
[Potential Feature] Allow searching for buildings

### ISSUE THREAD

**Issue by burschc** [burschc/CEN3031-Project-Group92#8]
### Task
Allow the search bar to look for specific buildings.

### User Story
As a user, I can type in the name of my dorm/student's dorm and easily see parking around it. Additionally, as a student, I can search for buildings my classes will be in and find their parking.

**Comment by yomole** [comment]
This can be assigned both to front and back end. There is nothing restricting multiple users working on an issue.
